# Generated by Django 3.0.7 on 2020-07-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(max_length=255, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('foto', models.FileField(max_length=150, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='personas_imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='fotos')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimiento.personas')),
            ],
        ),
        migrations.CreateModel(
            name='datos_personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('presion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimiento.personas')),
            ],
        ),
    ]
